import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { useRouter } from "next/router";
import apiClient from "@/lib/apiClient";

interface Post {
  id: number;
  title: string;
  content: string;
}

type Props = {
  posts: Post[];
};

// ISR 例：1日ごとに更新
export async function getStaticProps() {
  try {
    // axiosを使用してデータを取得
    const res = await apiClient.get("/read-all");

    return {
      props: {
        posts: res.data,
      },
      revalidate: 60 * 60 * 24,
    };
  } catch (err) {
    console.log(err);
  }
}

export default function Home({ posts }: Props) {
  const router = useRouter();

  // 投稿を削除する
  const handleDelete = async (postId: number) => {
    try {
      // axiosを使用してデータを削除
      const res = await apiClient.delete("/delete", {
        params: { id: postId },
      });

      router.reload();
    } catch (err) {
      alert("削除に失敗しました。");
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.homeContainer}>
        <div>
          {posts.map((post: Post) => (
            <div key={post.id} className={styles.postCard}>
              <Link href={`posts/${post.id}`} className={styles.postCardBox}>
                <h2>{post.title}</h2>
              </Link>
              <p>{post.content}</p>
              <Link href={`/edit-post/${post.id}`}>
                <button className={styles.editButton}>編集</button>
              </Link>

              <button className={styles.deleteButton} onClick={() => handleDelete(post.id)}>
                削除
              </button>
            </div>
          ))}
        </div>
      </div>
    </>
  );
}
